project:
  type: website
  output-dir: docs
#  site-url: https://bridgepaediatrics.github.io/quarto/
#  base-url: /quarto/ #these weren't helping
# options for this are shown in https://quarto.org/docs/websites/website-navigation.html  

# the code is sensitive to how much tab indentation there is
site: 
  #when I change the output directory here, I lose my formatting
#  output_dir: docs
  #author: "Neil Lawrence"

website:
  title: "Bridge Paediatrics Website"
  description: "A paediatric resource for parents and healthcare professionals."
  site-url: "https://bridgepaediatrics.github.io/quarto/"
  
  navbar:
   # select icons from here with their name https://icons.getbootstrap.com/
    tools: 
      - icon: youtube
        href: https://www.youtube.com/channel/UC7ri7i0YPUt0empuq_JWu4Q
      - icon: twitter-x
        href: https://x.com/BridgePaedsR_yh
      - icon: google
        href: mailto:bridge.paedsresearch.yh@gmail.com #
  
    background: purple
  
    foreground: white
  
    search: true
  
    logo: images/Bridge_logo_circle.png
  
    logo-alt: "Run by PGDiT:" #I presume this is rendered if the device can't render an image
    
    pinned: true #whether to always show the nav bar
    
    collapse: true #collapse the navbar items when its a narrow view
    left:
      - href: index.qmd
        text: Home
#      - about.qmd

      - href: committee.qmd
        text: Committee members
        
      - href: previous_videos.qmd
        text: Previous Research Training Videos
        
      - href: upcoming_opportunities.qmd
        text: Upcoming opportunities

format:
  
  html:
  
    theme: cosmo
  
    css: styles.css
  
    toc: false #this stops the index 'on this page' appearing in the top right of the page

editor: visual


