---
title: "<h1 style='text-align: center;'>Previous Bridge Paediatrics Online Events</h1>"
toc: false
---

::: {style="text-align: center;"}


:::

::: {style="text-align: center;"}
# Insights from research in Malawi

## Dr Charlotte Fuller, a paediatric registrar currently working at Sheffield Children's Hospital, takes us through her passion for performing research in low to middle income countries, and the interesting differences and challenges this presents.
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/zx1IrIAzGao?si=7xMMSMv4roRT5GTf;start=3" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Research into Cystic Fibrosis

## Professor Tim Lee, Lead Clinician and Consultant at the Leeds Regional Paediatric Cystic Fibrosis Centre, takes us through an emotional rollercoaster of the benefits of research for patients with cystic fibrosis, with helpful hints and tips about how to get into research along the way.
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/WgWZWyhffD0?si=TdlQym3OguiLOZlb&amp;start=128" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Research collaboration - ideas for research that doesn't require extra funding

## Dr Neil Lawrence, an NIHR Doctoral Research Fellow undertaking a PhD in applied data science shares ideas and offers for research collaboration in paediatrics that can be undertaken without the requirement of extra funding.
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/krDPfwMkHGc?si=E6A2pdqN4gyySgaI&amp;start=70" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Writing Book Chapters and Tips for Publishing

## Professor Will Carroll, the inspiring author of the 'Illustrated Textbook of Paediatrics' as well as recommended texts for the MRCPCH exam such as 'Clinical Cases for MRCPCH Theory and Science takes us through his hints and tips for how to get into professional medical science publishing.
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/l-1MFGdbZII?si=z97K9-CnIh6pIDlE&amp;start=146" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Clinical Questions for the RCPCH e-Portfolio

## Dr Anna Fox, ST8 Paediatrics Trainee takes us through how to maximise the value of completing a PICO research question (Population, Intervention, Comparator and Outcome) within the e-portfolio
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/kvqyz-siv5s?si=rrl-Qh2w4924BgBM&amp;start=50" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Artificial Intelligence Frontiers: Transforming Paediatric Research

## Professor Paul Dimitri, Vice President for Science and Research at the Royal College of Paediatrics and Child Health and Consultant Paediatric Endocrinologist
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/gIZ67VQiXQI?si=BK96bwhtRZZE5XMm&amp;start=128" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Quality Improvement Projects from Neonatology in Leeds Suitable for Multicentre Extension

## Dr Ourania Pappa, Paediatrician with Neonatal Special Interest
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/9gcF1BntZFg?si=2d3s6R9lR7Ll57nm&amp;start=163" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Journal Club - Risk Factors for Asthma Attacks and Poor Control in Children

## Rumbie Jhamba and Haji Khan, Consultant Paediatrician
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/eVWDeR_HZ6Q?si=6aahiZAPZfaaYMS5&amp;start=5" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Turning Quality Improvement Projects into Publications and Presentations

## Aoife Hurley, Neonatal Registrar
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/tZE8iFfBQe0?si=HgFgA4Knfs9Vt45h&amp;start=82" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Journal Club: Exclusive Breastfeeding Duration and the Risk of Childhood Cancers

## Aala Farah and Jess Morgan, Consultant Paediatric Oncologist
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/f5rbrXlfhNc?si=62nMu1JFTZc0Fx_x&amp;start=160" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Statistics for clinical researchers

## Jeremy Dawson, Professor of Statistics
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/RFyOnOHSjqg?si=-QtDjBrhmGnEU5DQ&amp;start=33" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Patient and Public Involvement in Research

## Bob Phillips, Professor of Paediatric Oncology
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://www.youtube.com/embed/2Nf6fhkOoQg?si=8verGBhp8VybGqA-&amp;start=183" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Introduction to the COMET Study in Neonatology

## Kathryn Johnson, Consultant Neonatologist
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://drive.google.com/file/d/1y5yTe-WDVuLhSXj5ZmTly65chIbTwNNr/preview" allow="autoplay"></iframe>

:::
:::

::: {style="text-align: center;"}
# Building A Journal Club

## Sean O’Riordan, Consultant in Paediatric Infectious Diseases
:::

::: {.iframe-container}
::: {.responsive-iframe}

<iframe src="https://drive.google.com/file/d/1WYapG6KjHUu1ABQn2Zz9GJcUiPmaIh73/preview;start=23" allow="autoplay"></iframe>

:::
:::
